name: 'CI'

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lisp:
          - sbcl-bin

    env:
      ON_CI_SERVER: 1
      QUICKLISP_ADD_TO_INIT_FILE: true
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v3
      
      # Install system dependencies first
      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      # Install SBCL and Quicklisp
      - name: Setup Common Lisp
        uses: 40ants/setup-lisp@v2
        with:
          asdf-system: loam

      # Run the tests
      - name: Run tests
        run: |
          ros -e '(ql:quickload :loam :silent t)' \
              -e '(asdf:test-system :loam)'